Remove CodeCov and semantic-release
ibi-group/otp-admin-ui pull request #40
Opened 2021-05-19 20:35 UTC by evansiroky

This PR:

- removes CodeCov from the CI process
- removes semantic-release entirely as there should be no need to publish this project as a package on npm

2021-05-19 20:59 UTC, landonreed commented on .github/workflows/node-ci.yml
> -          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
There's no need to publish to npm, but it's still nice to have semver handled for us (plus release notes).

2021-05-19 21:00 UTC, landonreed requested changes
I still think we should run `semantic-release` to handle release notes etc.

2021-05-21 04:56 UTC, evansiroky commented
Just added back semantic-release and configured it so that it doesn't publish to NPM.

2021-05-21 13:37 UTC, binh-dam-ibigroup approved these changes

2021-05-26 19:33 UTC, landonreed approved these changes

2021-05-26 19:33 UTC, merged